:; m="$CLAUDEFLOWS_MODE"; [ -z "$m" ] && [ -f .claudeflows/mode ] && m=$(tr -d '[:space:]' < .claudeflows/mode 2>/dev/null); if [ -z "$m" ]; then if [ -n "$CLAUDEFLOWS_QUIET" ] || [ -f .claudeflows/quiet ]; then m=off; else m=suggest; fi; fi; case "$m" in off) ;; auto) echo "claudeflows [mode: auto]: when the user's request clearly matches a flow, announce it and invoke the skill. Bug/regression/failing test: cf-bug. New feature or PRD task: cf-feature. Requirements/PRD: cf-prd. Rough idea to explore: cf-brainstorm. Review the pending diff: cf-precommit-review. Question needing a researched cited answer: cf-question. Never route follow-up turns inside work already in progress, trivial edits, directly answerable questions, or thinking-out-loud. The user can change this with /cf-mode." ;; *) echo "claudeflows [mode: suggest]: flows run only with user consent. When a request clearly matches a flow, offer it in one short line — e.g. 'This looks like a cf-bug case — want the full flow, or a direct fix?' — and invoke the skill only if the user agrees; otherwise handle the request directly. If the user declines, do not offer again this session. Explicit /cf-* commands always run. Flows: cf-bug (bug/regression/failing test), cf-feature (new feature or PRD task), cf-prd (requirements/PRD), cf-brainstorm (rough idea to explore), cf-precommit-review (pending diff review), cf-question (researched cited answer). Never offer for follow-up turns inside work already in progress, trivial edits, directly answerable questions, or thinking-out-loud. The user can change this with /cf-mode." ;; esac; exit 0
@echo off
set "CFMODE="
if exist .claudeflows\mode set /p CFMODE=<.claudeflows\mode
if defined CLAUDEFLOWS_MODE set "CFMODE=%CLAUDEFLOWS_MODE%"
if not defined CFMODE if defined CLAUDEFLOWS_QUIET exit /b 0
if not defined CFMODE if exist .claudeflows\quiet exit /b 0
if not defined CFMODE set "CFMODE=suggest"
if /i "%CFMODE%"=="off" exit /b 0
if /i "%CFMODE%"=="auto" echo claudeflows [mode: auto]: when the user's request clearly matches a flow, announce it and invoke the skill. Bug/regression/failing test: cf-bug. New feature or PRD task: cf-feature. Requirements/PRD: cf-prd. Rough idea to explore: cf-brainstorm. Review the pending diff: cf-precommit-review. Question needing a researched cited answer: cf-question. Never route follow-up turns inside work already in progress, trivial edits, directly answerable questions, or thinking-out-loud. The user can change this with /cf-mode.
if /i "%CFMODE%"=="auto" exit /b 0
echo claudeflows [mode: suggest]: flows run only with user consent. When a request clearly matches a flow, offer it in one short line — e.g. 'This looks like a cf-bug case — want the full flow, or a direct fix?' — and invoke the skill only if the user agrees; otherwise handle the request directly. If the user declines, do not offer again this session. Explicit /cf-* commands always run. Flows: cf-bug (bug/regression/failing test), cf-feature (new feature or PRD task), cf-prd (requirements/PRD), cf-brainstorm (rough idea to explore), cf-precommit-review (pending diff review), cf-question (researched cited answer). Never offer for follow-up turns inside work already in progress, trivial edits, directly answerable questions, or thinking-out-loud. The user can change this with /cf-mode.
exit /b 0
